base-s100000-biasFalse:
    offshore_mods:
        wake_model: base
        offshore_threshold: 100000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


base-s75000-biasFalse:
    offshore_mods:
        wake_model: base
        offshore_threshold: 75000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


base-s50000-biasFalse:
    offshore_mods:
        wake_model: base
        offshore_threshold: 50000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


base-s25000-biasFalse:
    offshore_mods:
        wake_model: base
        offshore_threshold: 25000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


base-s10000-biasFalse:
    offshore_mods:
        wake_model: base
        offshore_threshold: 10000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


base-s7500-biasFalse:
    offshore_mods:
        wake_model: base
        offshore_threshold: 7500
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


base-s5000-biasFalse:
    offshore_mods:
        wake_model: base
        offshore_threshold: 5000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


base-s2500-biasFalse:
    offshore_mods:
        wake_model: base
        offshore_threshold: 2500
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


base-s1000-biasFalse:
    offshore_mods:
        wake_model: base
        offshore_threshold: 1000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


standard-s100000-biasFalse:
    offshore_mods:
        wake_model: standard
        offshore_threshold: 100000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


standard-s75000-biasFalse:
    offshore_mods:
        wake_model: standard
        offshore_threshold: 75000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


standard-s50000-biasFalse:
    offshore_mods:
        wake_model: standard
        offshore_threshold: 50000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


standard-s25000-biasFalse:
    offshore_mods:
        wake_model: standard
        offshore_threshold: 25000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


standard-s10000-biasFalse:
    offshore_mods:
        wake_model: standard
        offshore_threshold: 10000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


standard-s7500-biasFalse:
    offshore_mods:
        wake_model: standard
        offshore_threshold: 7500
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


standard-s5000-biasFalse:
    offshore_mods:
        wake_model: standard
        offshore_threshold: 5000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


standard-s2500-biasFalse:
    offshore_mods:
        wake_model: standard
        offshore_threshold: 2500
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


standard-s1000-biasFalse:
    offshore_mods:
        wake_model: standard
        offshore_threshold: 1000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


glaum-s100000-biasFalse:
    offshore_mods:
        wake_model: glaum
        offshore_threshold: 100000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


glaum-s75000-biasFalse:
    offshore_mods:
        wake_model: glaum
        offshore_threshold: 75000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


glaum-s50000-biasFalse:
    offshore_mods:
        wake_model: glaum
        offshore_threshold: 50000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


glaum-s25000-biasFalse:
    offshore_mods:
        wake_model: glaum
        offshore_threshold: 25000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


glaum-s10000-biasFalse:
    offshore_mods:
        wake_model: glaum
        offshore_threshold: 10000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


glaum-s7500-biasFalse:
    offshore_mods:
        wake_model: glaum
        offshore_threshold: 7500
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


glaum-s5000-biasFalse:
    offshore_mods:
        wake_model: glaum
        offshore_threshold: 5000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


glaum-s2500-biasFalse:
    offshore_mods:
        wake_model: glaum
        offshore_threshold: 2500
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


glaum-s1000-biasFalse:
    offshore_mods:
        wake_model: glaum
        offshore_threshold: 1000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


new_more-s100000-biasFalse:
    offshore_mods:
        wake_model: new_more
        offshore_threshold: 100000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


new_more-s75000-biasFalse:
    offshore_mods:
        wake_model: new_more
        offshore_threshold: 75000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


new_more-s50000-biasFalse:
    offshore_mods:
        wake_model: new_more
        offshore_threshold: 50000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


new_more-s25000-biasFalse:
    offshore_mods:
        wake_model: new_more
        offshore_threshold: 25000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


new_more-s10000-biasFalse:
    offshore_mods:
        wake_model: new_more
        offshore_threshold: 10000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


new_more-s7500-biasFalse:
    offshore_mods:
        wake_model: new_more
        offshore_threshold: 7500
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


new_more-s5000-biasFalse:
    offshore_mods:
        wake_model: new_more
        offshore_threshold: 5000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


new_more-s2500-biasFalse:
    offshore_mods:
        wake_model: new_more
        offshore_threshold: 2500
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False


new_more-s1000-biasFalse:
    offshore_mods:
        wake_model: new_more
        offshore_threshold: 1000
        onshore_threshold: False
    renewable:
        onwind:
            resource:
                bias_corr: False
        offwind-combined:
            resource:
                bias_corr: False